# Generated by Django 5.2.6 on 2025-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, help_text='Например: 6-4, 3-6, 7-5', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт (ищет соперника)'), ('scheduled', 'Запланирован'), ('finished', 'Завершён')], default='open', max_length=20),
        ),
    ]
