# Generated by Django 5.2.6 on 2025-09-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('level', models.CharField(choices=[('1.0', 'NTRP 1.0'), ('1.5', 'NTRP 1.5'), ('2.0', 'NTRP 2.0'), ('2.5', 'NTRP 2.5'), ('3.0', 'NTRP 3.0'), ('3.5', 'NTRP 3.5'), ('4.0', 'NTRP 4.0'), ('4.5', 'NTRP 4.5'), ('5.0', 'NTRP 5.0'), ('5.5', 'NTRP 5.5'), ('6.0', 'NTRP 6.0'), ('6.5', 'NTRP 6.5'), ('7.0', 'NTRP 7.0')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players_photos/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес проживания')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='achievements_photos/')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('format', models.PositiveIntegerField(choices=[(16, '16 игроков'), (32, '32 игрока'), (64, '64 игрока (группы + плей-офф)')], default=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('players', models.ManyToManyField(blank=True, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('players', models.ManyToManyField(blank=True, to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='players.tournament')),
            ],
        ),
    ]
